server:
  port: 8080
  servlet:
    context-path: /

spring:
  messages:
    encoding: UTF-8
    basename: i18n/validation/message  # 要定义到文件名这个层次
    always-use-message-format: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useServerPrepStmts=false&allowMultiQueries=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      pool-name: DatebookHikariCP
      max-lifetime: 20000
      connection-timeout: 10000
      connection-test-query: SELECT 1
  mail:
    host: smtp.163.com
    username: llg3904@163.com
    password: 8023you
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 300Mb
#  activemq:
#    broker-url: tcp://192.168.145.128:61616
#  cache:
#    type: caffeine


file:
  path: D:/Other/upload/
  url: http://localhost:8000/
# Log
logging:
  level:
    org.springframework: DEBUG
    com.xxx.notes.mapper: DEBUG

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.xxx.notes.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    use-column-label: true


